# Generated by Django 5.0.1 on 2024-02-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediatype',
            old_name='title',
            new_name='name',
        ),
    ]
