# Generated by Django 5.0.1 on 2024-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_title_mediatype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='alpha2',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='alpha3t',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
